name: Good Ci/Cd

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Билд приложения"
    - npm install --cache /path/to/cache
    - npm run build
  locks:
    max-run: 1

deploy:
  stage: deploy
  script:
    - echo "Деплой прилоежния"
    - rm -rf /path/to/deployment
    - cp -r dist/* /path/to/deployment
  environment:
    DEPLOYMENT_PATH: /path/to/deployment
  artifacts:
    paths:
      - dist/*